// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Context;

namespace api.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20210730194608_Sampledata1")]
    partial class Sampledata1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("api.Entities.Cast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            Id = 15,
                            Character = "Iris Marquez",
                            MovieId = 1,
                            name = "Elisa Waves"
                        },
                        new
                        {
                            Id = 6,
                            Character = "Greco Rodrigues",
                            MovieId = 1,
                            name = "Karchez"
                        },
                        new
                        {
                            Id = 7,
                            Character = "Fedor",
                            MovieId = 1,
                            name = "Carola"
                        },
                        new
                        {
                            Id = 8,
                            Character = "carola",
                            MovieId = 2,
                            name = "carola"
                        },
                        new
                        {
                            Id = 9,
                            Character = "toni gambino",
                            MovieId = 2,
                            name = "auron"
                        },
                        new
                        {
                            Id = 10,
                            Character = "elisa",
                            MovieId = 3,
                            name = "Elisa Waves"
                        },
                        new
                        {
                            Id = 11,
                            Character = "Ronnie",
                            MovieId = 3,
                            name = "Ronnie 6"
                        });
                });

            modelBuilder.Entity("api.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Serie De gta Rolplay, ooc: muy buena",
                            Name = "Marbella Vice"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Serie de Minecract creada por Auron",
                            Name = "TortillaLand"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Seria de el juego Day Z con duracion de 14 Dias",
                            Name = "14Days"
                        });
                });

            modelBuilder.Entity("api.Entities.Cast", b =>
                {
                    b.HasOne("api.Entities.Movie", "Movie")
                        .WithMany("Casts")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("api.Entities.Movie", b =>
                {
                    b.Navigation("Casts");
                });
#pragma warning restore 612, 618
        }
    }
}
